"""add station info and multi-hour rainfall to observations

Revision ID: 669cacc62c48
Revises: 9fe183fd1e11
Create Date: 2026-05-07 09:56:39.272258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "669cacc62c48"
down_revision: Union[str, Sequence[str], None] = "9fe183fd1e11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rainfall_observations",
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "rainfall_observations",
        sa.Column("station_id", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "rainfall_observations",
        sa.Column("station_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "rainfall_observations",
        sa.Column("county_name", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "rainfall_observations",
        sa.Column("town_name", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "rainfall_observations", sa.Column("rainfall_1hr", sa.Float(), nullable=True)
    )
    op.add_column(
        "rainfall_observations", sa.Column("rainfall_3hr", sa.Float(), nullable=True)
    )
    op.add_column(
        "rainfall_observations", sa.Column("rainfall_24hr", sa.Float(), nullable=True)
    )
    op.create_index(
        "rainfall_observations_location_idx",
        "rainfall_observations",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "rainfall_observations_location_idx",
        table_name="rainfall_observations",
        postgresql_using="gist",
    )
    op.drop_column("rainfall_observations", "rainfall_24hr")
    op.drop_column("rainfall_observations", "rainfall_3hr")
    op.drop_column("rainfall_observations", "rainfall_1hr")
    op.drop_column("rainfall_observations", "town_name")
    op.drop_column("rainfall_observations", "county_name")
    op.drop_column("rainfall_observations", "station_name")
    op.drop_column("rainfall_observations", "station_id")
    op.drop_column("rainfall_observations", "location")
    # ### end Alembic commands ###
