"""add districts table

Revision ID: 75366618256b
Revises: 600b24bfc3e6
Create Date: 2026-05-04 10:57:45.467145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "75366618256b"
down_revision: Union[str, Sequence[str], None] = "600b24bfc3e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("town_id", sa.String(length=10), nullable=False),
        sa.Column("town_code", sa.String(length=20), nullable=True),
        sa.Column("town_name", sa.String(length=50), nullable=False),
        sa.Column("town_eng", sa.String(length=100), nullable=True),
        sa.Column("county_id", sa.String(length=10), nullable=False),
        sa.Column("county_code", sa.String(length=20), nullable=True),
        sa.Column("county_name", sa.String(length=50), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("town_id"),
    )
    op.create_index(
        "districts_geometry_idx",
        "districts",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "districts_geometry_idx", table_name="districts", postgresql_using="gist"
    )
    op.drop_table("districts")
    # ### end Alembic commands ###
