"""add flood_risk_zones table

Revision ID: 7827f205ac17
Revises: 75366618256b
Create Date: 2026-05-05 14:14:03.411155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7827f205ac17'
down_revision: Union[str, Sequence[str], None] = '75366618256b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flood_risk_zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('flood_risk_zones_geometry_idx', 'flood_risk_zones', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('flood_risk_zones_geometry_idx', table_name='flood_risk_zones', postgresql_using='gist')
    op.drop_table('flood_risk_zones')
    # ### end Alembic commands ###
