"""add district and flood risk to properties

Revision ID: 9fe183fd1e11
Revises: 7827f205ac17
Create Date: 2026-05-05 16:46:13.595620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe183fd1e11'
down_revision: Union[str, Sequence[str], None] = '7827f205ac17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('district_name', sa.String(length=100), nullable=True))
    op.add_column('properties', sa.Column('flood_risk_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'flood_risk_level')
    op.drop_column('properties', 'district_name')
    # ### end Alembic commands ###
